src/LexemeWebApp/Lexeme/Controllers/SiberianTatarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lexeme.Models;
using Lexeme.Dal;

namespace Lexeme.Controllers
{
    public class SiberianTatarController : Controller
    {
        public WordViewModel wordViewModel;
        public List<SelectListItem> listSelectListItems;

        public FragmentViewModel fragmentViewModel;

        public SiberianTatarController()
        {
            wordViewModel = new WordViewModel();
            listSelectListItems = new List<SelectListItem>();
            List<WordSty> words = new WordDal().GetWordListSty();

            foreach (Word word in words)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = word.WordText,
                    Value = word.Id.ToString(),
                    Selected = false
                };
                listSelectListItems.Add(selectList);
            }

            wordViewModel.Words = listSelectListItems;

            fragmentViewModel = new FragmentViewModel();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(wordViewModel);
        }

        [HttpPost]
        public ActionResult Index(IEnumerable<string> selectedWordText)
        {
            //wordViewModel.Words = listSelectListItems;
            if (selectedWordText == null)
            {
                ViewBag.Message = "No words are selected";
            }
            else
            {
                //StringBuilder sb = new StringBuilder();
                //sb.Append("You selected – " + string.Join(",", selectedCities));
                ViewBag.Message = selectedWordText.ToArray()[0];
            }

            return View(wordViewModel);
        }

        [HttpGet]
        public ActionResult Context(string word)
        {
            ViewBag.Message = word;

            return View(fragmentViewModel);
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

src/LexemeWebApp/Lexeme/Views/SiberianTatar/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>About Siberian Tatar</h4>
<p><b>Corpus and talking dictionary for Siberian Tatar are currently in progress... Please wait...</b> At the moment, here is just general information of data for our Siberian Tatar corpus.</p>
<p>
    Our first expedition was undertaken to Siberian Tatar village Ilchebaga (Ust’-Ishimsky District, Omsk Oblast, Siberia, Russia) in 2020. We recorded the speech data of 10 speakers (see table below) in this first expedition.
    These speech data are available in our work repository on GitHub and licensed under a Creative Commons Attribution 4.0 license (CC BY 4.0): <a href="https://github.com/ubaleht/SiberianTatar">Siberian Tatar</a>
</p>
<p><b>Description of Speakers:</b></p>
<table width="600">
    <thead>
        <tr>
            <th>The Code of the <br /> Speaker and <br /> Gender</th>
            <th>The Year <br /> of Birth</th>
            <th>Speech Data <br /> (Duration, In Minutes)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>AVN-69 (M)</td>
            <td>1969</td>
            <td>2,5</td>
        </tr>
        <tr>
            <td>GMG-67 (M)</td>
            <td>1967</td>
            <td>2,5</td>
        </tr>
        <tr>
            <td>GNSh-29 (F)</td>
            <td>1929</td>
            <td>24,5</td>
        </tr>
        <tr>
            <td>KMM-63 (M)</td>
            <td>1963</td>
            <td>49</td>
        </tr>
        <tr>
            <td>MKhU-50 (F)</td>
            <td>1950</td>
            <td>32</td>
        </tr>
        <tr>
            <td>MRCh-60 (M)</td>
            <td>1960</td>
            <td>34</td>
        </tr>
        <tr>
            <td>NGA-45 (F)</td>
            <td>1945</td>
            <td>12</td>
        </tr>
        <tr>
            <td>NIA-53 (M)</td>
            <td>1953</td>
            <td>9</td>
        </tr>
        <tr>
            <td>SGL-61 (M)</td>
            <td>1961</td>
            <td>5</td>
        </tr>
    </tbody>
</table>
<br />
<p>
    We undertook the second expedition in 2021 to the villages Ilchebaga (Ust’-Ishimsky District) and Tavinsk (Tevriz District) Omsk Oblast, Siberia, Russia.
    We recorded about 5 hours of audio and 1 hour video from 13 speakers from our second expedition. These data have not yet been published. If you are interested in this audio and video data, then write to <a href="/Home/Contact">the author of this site</a>. An example of a video from this expedition, see below.
</p>
<br />
<p>
    <iframe width="490" height="320" src=https://www.youtube.com/embed/xD_0v8xjJSs
            frameborder="0" allowfullscreen></iframe>
</p>
<br />
<p><b>Map of the dialects of the Siberian Tatar language:</b></p>
<img src="/Content/sibtat.png" width="444" height="349" border="0" alt="Map of the dialects of the Siberian Tatar language">
<p>This image of map of dialects is protected by copyright. <a href="https://turkic.elegantlexicon.com/lx.php?lx=stt">Copyright &#169; 2018-2022 Christopher A. Straughn.</a></p>

src/LexemeWebApp/Lexeme/Views/SiberianTatar/Context.cshtml
@using Lexeme.Models
@model FragmentViewModel
@{
                /**/

                ViewBag.Title = "Context";
                Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Word context</h4><br />

<!--<p>@Html.ActionLink("Back", "Index", "SiberianTatar")</p>-->

@if (ViewBag.Message != null)
{
    Model.GetFragmentByWordIdSty(@ViewBag.Message);
    <p>
        <b>Speaker's speech:</b> @Model.SpeakerSpeechesByFragment<br />
        <b>Speaker's speech (Common Turkic Alphabet):</b> @Model.SpeakerSpeechesByFragmentLatin<br />
        <b>Translation into English of the speaker's speech:</b> @Model.SpeakerSpeechesByFragmentEnTranslation<br />
        <b>Speaker Speech, Translate to Russian:</b> @Model.SpeakerSpeechesByFragmentRuTranslation<br />
        <b>Speaker Speech, Translate to Turkish:</b> @Model.SpeakerSpeechesByFragmentTrTranslation<br />
        <b>Interviewer's speech:</b> @Model.InterviewerSpeechesByFragment<br />
        <b>Translation into English of the interviewer's speech:</b> @Model.InterviewerSpeechesByFragmentEnTranslation<br />
        <b>Translation into Turkish of the interviewer's speech:</b> @Model.InterviewerSpeechesByFragmentTrTranslation<br />
        <b>Audio file Name:</b> @Model.FileName<br />
        <b>Fragment start time (in seconds):</b> @Model.Start<br />
        <b>Fragment end time (in seconds):</b> @Model.Finish<br />
        <audio id="myAudio">
            <source src="/Content/@Model.FileName#t=@Model.Start.ToString(),@Model.Finish.ToString()" type="audio/wav">
            Your browser does not support the audio element.
        </audio>
        <br />
    <p>
        <button onclick="playAudio()" id="playButton" type="button">Play Audio</button><br />
    </p>
    </p>
    <script>
            var x = document.getElementById("myAudio");
            var playButton = document.getElementById("playButton");

            function playAudio() {
                x.play();
                playButton.disabled = true;
            }

    </script>
}

<a href="javascript:void(0);" onclick="history.go(-1);">Back</a>

src/LexemeWebApp/Lexeme/Views/SiberianTatar/Index.cshtml
@using Lexeme.Models
@model WordViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>The Siberian Tatar Language</h4><br />
<div align="left">
    <table width="500" border="0" cellpadding="10" cellspacing="0">
        <tr>
            <td width="50%" align="left" valign="top">
                <div style="font-family:Arial">
                    @using (Html.BeginForm())
                    {
                        @Html.ListBoxFor(m => m.SelectedWordText, Model.Words, new { size = 16 })
                        <br />
                        <br />
                        <br />
                        <input type="submit" value=" See Info " />
                    }
                </div>
            </td>
            <td width="50%" align="left" valign="top">
                @if (ViewBag.Message != null)
                {
                    Model.GetWordByIdSty(@ViewBag.Message);
                <p>
                    <b>Selected word:</b> @Model.WordsText<br />
                    <b>Word (Common Turkic Alphabet):</b> @Model.SpeakerWordTextLatin<br />
                    <b>Translation in English:</b> @Model.SpeakerEnTranslate<br />
                    <b>Translation in Russian:</b> @Model.SpeakerRuTranslate<br />
                    <b>Translation in Turkish:</b> @Model.SpeakerTrTranslate<br />
                    <b>Morphology:</b> @Model.SpeakerMorph<br />
                    <b>Comments:</b> @Model.SpeakerComments<br />
                    <b>Speaker Info:</b> @Model.SpeakerPersonalInfo<br />
                    <b>Interviwer:</b> Ivan Ubaleht<br />
                    <b>Place, Date:</b> @Model.RecContext<br />
                    <br />
                    <b>Get the word's context:</b> @Html.ActionLink("Get context", "Context", "SiberianTatar", new { word = @ViewBag.Message }, htmlAttributes: null)
                </p><br />
                    <audio id="myAudio">
                        <source src="/Content/@Model.AudioFileName#t=@Model.Start.ToString(),@Model.Finish.ToString()" type="audio/wav">
                        Your browser does not support the audio element.
                    </audio>
                    <p></p>
                    <p>
                        <button onclick="playAudio()" id="playButton" type="button">Play Audio</button><br />
                        <div id="label1">Click the button to play the audio.</div><div id="label2" hidden>Click the button "See Info" to play the audio again.</div>
                    </p>
                    <!--<button onclick="pauseAudio()" type="button">Pause Audio</button>-->
                    <script>
                        var x = document.getElementById("myAudio");
                        var playButton = document.getElementById("playButton");
                        var label1 = document.getElementById("label1");
                        var label2 = document.getElementById("label2");

                        function playAudio() {
                            x.play();
                            playButton.disabled = true;
                            label1.hidden = true;
                            label2.hidden = false;
                        }

                        function pauseAudio() {
                            x.pause();
                        }

                    </script>
                }
            </td>
        </tr>
    </table>
</div>