src/LexemeWebApp/Lexeme/Controllers/SiberianIngrianFinnishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lexeme.Models;
using Lexeme.Dal;

namespace Lexeme.Controllers
{
    public class SiberianIngrianFinnishController : Controller
    {
        public WordViewModel wordViewModel;
        public List<SelectListItem> listSelectListItems;

        public FragmentViewModel fragmentViewModel;

        public SiberianIngrianFinnishController()
        {
            wordViewModel = new WordViewModel();
            listSelectListItems = new List<SelectListItem>();
            List<Word> words = new WordDal().GetWordList();

            foreach (Word word in words)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = word.WordText,
                    Value = word.Id.ToString(),
                    Selected = false
                };
                listSelectListItems.Add(selectList);
            }

            wordViewModel.Words = listSelectListItems;

            fragmentViewModel = new FragmentViewModel();
        }

        // GET: SiberianIngrianFinnish
        /*public ActionResult Index()
        {
            WordViewModel wordViewModel = new WordViewModel();

            return View(wordViewModel);
        }*/

        [HttpGet]
        public ActionResult Index()
        {
            

            /*if (wordViewModel.SelectedWordText != null)
            {
                List<SelectListItem> selectedItems = wordViewModel.SelectedWordText;
                foreach (var Tea in selectedItems)
                {
                    Tea.Selected = true;
                    ViewBag.Message += Tea.Text + " | ";
                }
            }*/

            

            return View(wordViewModel);
        }

        [HttpPost]
        public ActionResult Index(IEnumerable<string> selectedWordText)
        {
            //wordViewModel.Words = listSelectListItems;
            if (selectedWordText == null)
            {
                ViewBag.Message = "No words are selected";
            }
            else
            {
                //StringBuilder sb = new StringBuilder();
                //sb.Append("You selected – " + string.Join(",", selectedCities));
                ViewBag.Message = selectedWordText.ToArray()[0];
            }

            return View(wordViewModel);
        }

        [HttpGet]
        public ActionResult Context(string word)
        {
            ViewBag.Message = word;

            return View(fragmentViewModel);
        }
    }
}

src/LexemeWebApp/Lexeme/Views/SiberianIngrianFinnish/Context.cshtml
@using Lexeme.Models
@model FragmentViewModel
@{
                /**/

                ViewBag.Title = "Context";
                Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Word context</h4><br />

<!--<p>@Html.ActionLink("Back", "Index", "SiberianIngrianFinnish")</p>-->

@if (ViewBag.Message != null)
{
    Model.GetFragmentByWordId(@ViewBag.Message);
    <p>
        <b>Speaker's speech:</b> @Model.SpeakerSpeechesByFragment<br />
        <b>Translation into English of the speaker's speech:</b> @Model.SpeakerSpeechesByFragmentEnTranslation<br />
        <!--<b>Speaker Speech, Translate to Russian:</b> @Model.SpeakerSpeechesByFragmentRuTranslation<br />-->
        <b>Interviewer's speech:</b> @Model.InterviewerSpeechesByFragment<br />
        <b>Translation into English of the interviewer's speech:</b> @Model.InterviewerSpeechesByFragmentEnTranslation<br />
        <b>Audio file Name:</b> @Model.FileName<br />
        <b>Fragment start time (in seconds):</b> @Model.Start<br />
        <b>Fragment end time (in seconds):</b> @Model.Finish<br />
        <audio id="myAudio">
            <source src="/Content/@Model.FileName#t=@Model.Start.ToString(),@Model.Finish.ToString()" type="audio/wav">
            Your browser does not support the audio element.
        </audio>
        <br />
        <p>
            <button onclick="playAudio()" id="playButton" type="button">Play Audio</button><br />
        </p>
    </p> 
        <script>
            var x = document.getElementById("myAudio");
            var playButton = document.getElementById("playButton");

            function playAudio() {
                x.play();
                playButton.disabled = true;
            }

        </script>
}

<a href="javascript:void(0);" onclick="history.go(-1);">Back</a>

src/LexemeWebApp/Lexeme/Views/SiberianIngrianFinnish/Index.cshtml
@using Lexeme.Models
@model WordViewModel
@{
    ViewBag.Title = "Siberian Ingrian Finnish words";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Siberian Ingrian Finnish Talking Dictionary</h4><br />
<div align="left">
    <table width="500" border="0" cellpadding="10" cellspacing="0">
        <tr>
            <td width="50%" align="left" valign="top">
                <div style="font-family:Arial">
                    @using (Html.BeginForm())
                    {
                        @Html.ListBoxFor(m => m.SelectedWordText, Model.Words, new { size = 16 })
                        <br />
                        <br />
                        <br />
                        <input type="submit" value=" See Info " />
                    }
                </div>
            </td>
            <td width="50%" align="left" valign="top">
                @if (ViewBag.Message != null)
                {
                    Model.GetWordById(@ViewBag.Message);
                <p>
                    <b>Selected word:</b> @Model.WordsText<br />
                    <b>Translation in English:</b> @Model.SpeakerEnTranslate<br />
                    <b>Translation in Russian:</b> @Model.SpeakerRuTranslate<br />
                    <b>Morphology:</b> @Model.SpeakerMorph<br />
                    <b>Comments:</b> @Model.SpeakerComments<br />
                    <b>Speaker Info:</b> @Model.SpeakerPersonalInfo<br />
                    <b>Interviwer:</b> Ivan Ubaleht<br />
                    <b>Place, Date:</b> @Model.RecContext<br />
                    <br />
                    <b>Get the word's context:</b> @Html.ActionLink("Get context", "Context", "SiberianIngrianFinnish", new { word = @ViewBag.Message }, htmlAttributes: null)
                </p><br />
                    <audio id="myAudio">
                        <source src="/Content/@Model.AudioFileName#t=@Model.Start.ToString(),@Model.Finish.ToString()" type="audio/wav">
                        Your browser does not support the audio element.
                    </audio>
                    <p></p>
                    <p>
                        <button onclick="playAudio()" id="playButton" type="button">Play Audio</button><br />
                        <div id="label1">Click the button to play the audio.</div><div id="label2" hidden>Click the button "See Info" to play the audio again.</div>
                    </p>
                    <!--<button onclick="pauseAudio()" type="button">Pause Audio</button>-->
                    <script>
                        var x = document.getElementById("myAudio");
                        var playButton = document.getElementById("playButton");
                        var label1 = document.getElementById("label1");
                        var label2 = document.getElementById("label2");

                        function playAudio() {
                            x.play();
                            playButton.disabled = true;
                            label1.hidden = true;
                            label2.hidden = false;
                        }

                        function pauseAudio() {
                            x.pause();
                        }

                    </script>
                }
            </td>
        </tr>
    </table>
</div>